#!/bin/bash

CWD=`pwd`

if [ -e $PWD/sources/poky ]; then
    OEROOT=$PWD/sources/poky
elif [ -e $PWD/sources/oe-core ]; then
    OEROOT=$PWD/sources/oe-core
else
   echo "Cannot find OE-Core! Aborting..."
   false
fi

. $OEROOT/oe-init-build-env $CWD/$1 > /dev/null

# if conf/local.conf not generated, no need to go further
if [ ! -e conf/local.conf ]; then
    clean_up && return 1
fi

cat <<EOF >> $PWD/conf/local.conf

MACHINE = "stm32mp15-disco"
DISTRO = "beaveros"
INHERIT += "rm_work"
BBMULTICONFIG += "coproc"

# BAMBIK_SOURCES = "1"
# DL_DIR ?= "/mnt/storage/yocto/downloads"
# SSTATE_DIR ?= "/mnt/storage/yocto/sstate-cache/"
# BB_GENERATE_MIRROR_TARBALLS = "1"

EOF

mkdir -p $PWD/conf/multiconfig
cat <<EOF >> $PWD/conf/multiconfig/coproc.conf

MACHINE = "stm32mp157c-dk2"
DISTRO = "zephyr"

EOF

LAYERS=" \
    $CWD/sources/meta-openembedded/meta-oe \
    $CWD/sources/meta-openembedded/meta-python \
    $CWD/sources/meta-openembedded/meta-networking \
    $CWD/sources/meta-openembedded/meta-filesystems \
    $CWD/sources/meta-arm/meta-arm-toolchain \
    $CWD/sources/meta-arm/meta-arm \
    $CWD/sources/meta-swupdate \
    $CWD/sources/meta-virtualization \
    $CWD/sources/meta-clang \
    $CWD/sources/meta-beaver \
    $CWD/sources/meta-stm32mp \
    $CWD/sources/meta-zephyr/meta-zephyr-core \
    $CWD/sources/meta-zephyr/meta-zephyr-bsp \
"

for layer in $LAYERS; do
    layer_name=`basename $layer`
    echo "Adding layer $layer_name"
    bitbake-layers add-layer $layer
done
